"""Concrete organization-type strategies."""

from __future__ import annotations

from org_intel.schemas.enums import OrganizationType
from org_intel.strategies.base import OrganizationStrategy

STRATEGY_REGISTRY: dict[OrganizationType, OrganizationStrategy] = {
    OrganizationType.CITY: OrganizationStrategy(
        organization_type=OrganizationType.CITY,
        display_name="City / Municipality",
        department_terms=[
            "City Council",
            "City Manager",
            "Finance",
            "Public Works",
            "Utilities",
            "Parks and Recreation",
            "Police",
            "Fire",
            "Community Development",
            "Engineering",
            "Procurement",
            "Purchasing",
        ],
        capital_source_terms=[
            "Capital Improvement Plan",
            "CIP",
            "Capital Budget",
            "Capital Projects",
            "Project Tracker",
        ],
        governance_terms=["City Council", "Agenda", "Minutes", "Legistar", "Granicus", "BoardDocs"],
        procurement_terms=["Bids", "RFPs", "RFQs", "Purchasing", "Procurement", "Vendor Portal"],
        master_plan_terms=["Comprehensive Plan", "Parks Master Plan", "Transportation Plan"],
        financial_doc_terms=["Adopted Budget", "ACFR", "Annual Budget", "Official Statement"],
        project_categories=[
            "streets",
            "water",
            "wastewater",
            "stormwater",
            "parks",
            "facilities",
            "public_safety",
        ],
        path_hints=["/budget", "/cip", "/finance", "/public-works", "/bids", "/procurement"],
    ),
    OrganizationType.COUNTY: OrganizationStrategy(
        organization_type=OrganizationType.COUNTY,
        display_name="County",
        department_terms=[
            "County Commission",
            "County Administrator",
            "Public Works",
            "Facilities",
            "Roads",
            "Sheriff",
            "Courts",
            "Finance",
            "Procurement",
        ],
        capital_source_terms=["Capital Improvement Plan", "CIP", "Capital Projects", "Facilities Plan"],
        governance_terms=["Board of Commissioners", "Agenda", "Minutes"],
        procurement_terms=["Bids", "RFPs", "Purchasing", "Procurement"],
        master_plan_terms=["Facilities Master Plan", "Transportation Plan"],
        financial_doc_terms=["Adopted Budget", "ACFR", "Capital Budget"],
        project_categories=["roads", "facilities", "public_safety", "courts", "parks"],
        path_hints=["/budget", "/cip", "/public-works", "/purchasing"],
    ),
    OrganizationType.WATER_DISTRICT: OrganizationStrategy(
        organization_type=OrganizationType.WATER_DISTRICT,
        display_name="Water / Wastewater District",
        department_terms=[
            "Board of Directors",
            "General Manager",
            "Engineering",
            "Operations",
            "Treatment",
            "Distribution",
            "Collection",
            "Regulatory Compliance",
            "Finance",
        ],
        capital_source_terms=[
            "Capital Improvement Plan",
            "CIP",
            "Water System Plan",
            "Wastewater Facilities Plan",
            "Master Plan",
        ],
        governance_terms=["Board of Directors", "Agenda", "Minutes"],
        procurement_terms=["Bids", "RFPs", "RFQs", "Procurement"],
        master_plan_terms=["Water Master Plan", "Wastewater Master Plan", "Integrated Resource Plan"],
        financial_doc_terms=["Budget", "ACFR", "Rate Study", "SRF"],
        project_categories=[
            "water_treatment",
            "distribution",
            "wastewater",
            "collection",
            "reuse",
            "storage",
        ],
        path_hints=["/engineering", "/cip", "/bids", "/board"],
    ),
    OrganizationType.UNIVERSITY: OrganizationStrategy(
        organization_type=OrganizationType.UNIVERSITY,
        display_name="Public University",
        department_terms=[
            "Board of Regents",
            "Board of Trustees",
            "President",
            "Facilities",
            "Campus Planning",
            "Capital Planning",
            "Procurement",
            "Auxiliary Enterprises",
        ],
        capital_source_terms=[
            "Capital Plan",
            "Campus Master Plan",
            "Capital Projects",
            "Facilities Plan",
        ],
        governance_terms=["Board of Regents", "Board of Trustees", "Agenda"],
        procurement_terms=["Purchasing", "RFPs", "RFQs", "Bids"],
        master_plan_terms=["Campus Master Plan", "Housing Master Plan"],
        financial_doc_terms=["Operating Budget", "Capital Budget", "Bond Documents"],
        project_categories=["academic", "housing", "utilities", "research", "athletics", "infrastructure"],
        path_hints=["/facilities", "/capital", "/procurement", "/planning"],
    ),
    OrganizationType.AIRPORT: OrganizationStrategy(
        organization_type=OrganizationType.AIRPORT,
        display_name="Airport Authority",
        department_terms=[
            "Airport Authority",
            "Aviation Department",
            "Engineering",
            "Operations",
            "Finance",
            "Procurement",
        ],
        capital_source_terms=[
            "Airport Capital Plan",
            "ACIP",
            "CIP",
            "FAA Grant",
            "Airport Master Plan",
        ],
        governance_terms=["Authority Board", "Commission", "Agenda"],
        procurement_terms=["Bids", "RFPs", "On-call", "Procurement"],
        master_plan_terms=["Airport Master Plan", "ALP"],
        financial_doc_terms=["Budget", "PFC", "AIP", "Bond Documents"],
        project_categories=["airside", "landside", "terminal", "runway", "taxiway", "parking"],
        path_hints=["/business", "/bids", "/capital", "/master-plan"],
    ),
    OrganizationType.SCHOOL_DISTRICT: OrganizationStrategy(
        organization_type=OrganizationType.SCHOOL_DISTRICT,
        display_name="School District",
        department_terms=[
            "School Board",
            "Superintendent",
            "Facilities",
            "Bond Program",
            "Procurement",
            "Operations",
        ],
        capital_source_terms=["Bond Program", "Capital Facilities Plan", "Facility Master Plan"],
        governance_terms=["School Board", "BoardDocs", "Agenda"],
        procurement_terms=["Bids", "RFPs", "Purchasing"],
        master_plan_terms=["Facility Master Plan", "Long Range Facilities Plan"],
        financial_doc_terms=["Budget", "Bond Official Statement"],
        project_categories=["school_construction", "modernization", "safety", "athletics"],
        path_hints=["/facilities", "/bond", "/bids", "/board"],
    ),
    OrganizationType.HOSPITAL: OrganizationStrategy(
        organization_type=OrganizationType.HOSPITAL,
        display_name="Public Hospital / Health System",
        department_terms=[
            "Governing Board",
            "Facilities",
            "Capital Planning",
            "Plant Operations",
            "Clinical Engineering",
            "Procurement",
        ],
        capital_source_terms=["Capital Budget", "Facilities Plan", "Master Plan"],
        governance_terms=["Board of Trustees", "Agenda"],
        procurement_terms=["Purchasing", "RFPs", "Contracting"],
        master_plan_terms=["Facilities Master Plan", "Campus Plan"],
        financial_doc_terms=["Budget", "Audited Financials"],
        project_categories=["clinical", "facilities", "infrastructure", "equipment"],
        path_hints=["/about", "/facilities", "/procurement"],
    ),
    OrganizationType.TRANSIT_AGENCY: OrganizationStrategy(
        organization_type=OrganizationType.TRANSIT_AGENCY,
        display_name="Transit Agency",
        department_terms=["Board", "General Manager", "Planning", "Engineering", "Procurement", "Operations"],
        capital_source_terms=["Transit Development Plan", "Capital Plan", "TIP"],
        governance_terms=["Board of Directors", "Agenda"],
        procurement_terms=["Procurement", "RFPs", "Bids"],
        master_plan_terms=["Long Range Transit Plan", "Fleet Plan"],
        financial_doc_terms=["Budget", "NTD", "Grant Documents"],
        project_categories=["fleet", "facilities", "guideway", "stations", "technology"],
        path_hints=["/procurement", "/planning", "/capital"],
    ),
    OrganizationType.STATE_AGENCY: OrganizationStrategy(
        organization_type=OrganizationType.STATE_AGENCY,
        display_name="State Agency",
        department_terms=["Director", "Divisions", "Capital Programs", "Procurement", "Finance"],
        capital_source_terms=["Capital Budget", "Program Plan", "STIP"],
        governance_terms=["Commission", "Board", "Legislature"],
        procurement_terms=["State Procurement", "RFPs", "Bids"],
        master_plan_terms=["Strategic Plan", "Facility Plan"],
        financial_doc_terms=["Budget Request", "Capital Budget"],
        project_categories=["infrastructure", "facilities", "technology"],
        path_hints=["/procurement", "/budget", "/projects"],
    ),
    OrganizationType.HOUSING_AUTHORITY: OrganizationStrategy(
        organization_type=OrganizationType.HOUSING_AUTHORITY,
        display_name="Housing Authority",
        department_terms=["Board", "Executive Director", "Development", "Procurement", "Maintenance"],
        capital_source_terms=["Capital Fund", "Development Plan", "RAD"],
        governance_terms=["Board of Commissioners", "Agenda"],
        procurement_terms=["Procurement", "RFPs", "Bids"],
        master_plan_terms=["Agency Plan", "Development Plan"],
        financial_doc_terms=["Budget", "HUD Reports"],
        project_categories=["housing", "rehab", "infrastructure"],
        path_hints=["/procurement", "/development", "/about"],
    ),
    OrganizationType.PARK_DISTRICT: OrganizationStrategy(
        organization_type=OrganizationType.PARK_DISTRICT,
        display_name="Park District",
        department_terms=["Board", "Executive Director", "Planning", "Parks", "Procurement"],
        capital_source_terms=["Capital Improvement Plan", "Parks Master Plan"],
        governance_terms=["Park Board", "Agenda"],
        procurement_terms=["Bids", "RFPs"],
        master_plan_terms=["Parks Master Plan", "Recreation Plan"],
        financial_doc_terms=["Budget", "Bond Documents"],
        project_categories=["parks", "trails", "recreation", "facilities"],
        path_hints=["/projects", "/budget", "/bids"],
    ),
    OrganizationType.PORT_AUTHORITY: OrganizationStrategy(
        organization_type=OrganizationType.PORT_AUTHORITY,
        display_name="Port Authority",
        department_terms=["Commission", "Executive Director", "Engineering", "Real Estate", "Procurement"],
        capital_source_terms=["Capital Plan", "Marine Terminal Plan"],
        governance_terms=["Port Commission", "Agenda"],
        procurement_terms=["Procurement", "RFPs", "Bids"],
        master_plan_terms=["Port Master Plan"],
        financial_doc_terms=["Budget", "Bond Documents"],
        project_categories=["marine", "terminal", "rail", "roadway", "facilities"],
        path_hints=["/business", "/procurement", "/projects"],
    ),
    OrganizationType.TRANSPORTATION_AUTHORITY: OrganizationStrategy(
        organization_type=OrganizationType.TRANSPORTATION_AUTHORITY,
        display_name="Transportation Authority",
        department_terms=["Board", "Executive Director", "Planning", "Engineering", "Procurement"],
        capital_source_terms=["Capital Plan", "Measure Program", "STIP"],
        governance_terms=["Board", "Agenda"],
        procurement_terms=["Procurement", "RFPs", "Bids"],
        master_plan_terms=["Long Range Transportation Plan"],
        financial_doc_terms=["Budget", "Sales Tax Reports"],
        project_categories=["roads", "transit", "bike_ped", "bridges"],
        path_hints=["/projects", "/procurement", "/planning"],
    ),
    OrganizationType.UTILITY_AUTHORITY: OrganizationStrategy(
        organization_type=OrganizationType.UTILITY_AUTHORITY,
        display_name="Utility Authority",
        department_terms=["Board", "General Manager", "Engineering", "Operations", "Procurement"],
        capital_source_terms=["Capital Improvement Plan", "System Plan"],
        governance_terms=["Board", "Agenda"],
        procurement_terms=["Bids", "RFPs", "Procurement"],
        master_plan_terms=["System Master Plan", "IRP"],
        financial_doc_terms=["Budget", "Rate Study"],
        project_categories=["generation", "distribution", "transmission", "water", "wastewater"],
        path_hints=["/engineering", "/cip", "/bids"],
    ),
    OrganizationType.JOINT_POWERS_AUTHORITY: OrganizationStrategy(
        organization_type=OrganizationType.JOINT_POWERS_AUTHORITY,
        display_name="Joint Powers Authority",
        department_terms=["Board", "Executive Director", "Member Agencies", "Procurement"],
        capital_source_terms=["Capital Plan", "Project List"],
        governance_terms=["JPA Board", "Agenda"],
        procurement_terms=["Procurement", "RFPs"],
        master_plan_terms=["Master Plan"],
        financial_doc_terms=["Budget"],
        project_categories=["regional_infrastructure"],
        path_hints=["/projects", "/procurement", "/board"],
    ),
    OrganizationType.OTHER_PUBLIC: OrganizationStrategy(
        organization_type=OrganizationType.OTHER_PUBLIC,
        display_name="Other Public / Quasi-Public",
        department_terms=["Board", "Executive", "Finance", "Procurement", "Engineering", "Facilities"],
        capital_source_terms=["Capital Plan", "Capital Budget", "Projects"],
        governance_terms=["Board", "Agenda", "Minutes"],
        procurement_terms=["Bids", "RFPs", "Procurement", "Purchasing"],
        master_plan_terms=["Master Plan"],
        financial_doc_terms=["Budget", "Audit", "ACFR"],
        project_categories=["facilities", "infrastructure"],
        path_hints=["/budget", "/projects", "/procurement", "/about"],
    ),
    OrganizationType.UNKNOWN: OrganizationStrategy(
        organization_type=OrganizationType.UNKNOWN,
        display_name="Unknown",
        department_terms=["Board", "Council", "Finance", "Procurement", "Engineering"],
        capital_source_terms=["Capital Improvement", "CIP", "Capital Projects", "Budget"],
        governance_terms=["Agenda", "Minutes", "Board"],
        procurement_terms=["Bids", "RFPs", "Procurement"],
        master_plan_terms=["Master Plan"],
        financial_doc_terms=["Budget", "ACFR"],
        project_categories=["infrastructure"],
        path_hints=["/budget", "/cip", "/bids", "/about"],
    ),
}
